# Generated by Django 4.1.5 on 2023-01-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.AlterModelOptions(
            name='user_inherit',
            options={'verbose_name_plural': 'user_info'},
        ),
    ]
