# Generated by Django 4.1.5 on 2023-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(max_length=200, to='Elearning_platform.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(max_length=200, to='Elearning_platform.teacher'),
        ),
    ]
