# Generated by Django 4.1.5 on 2023-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0002_delete_user_info_alter_user_inherit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inherit',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_inherit',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_inherit',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='first name'),
        ),
    ]
