# Generated by Django 4.1.5 on 2023-02-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0003_remove_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_inherit',
            name='image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
    ]
