# Generated by Django 4.1.5 on 2023-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0003_alter_user_inherit_address_alter_user_inherit_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inherit',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
