# Generated by Django 4.1.5 on 2023-01-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0005_course_student_teacher_studentteacher_studentcourse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teacher'},
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user_inherit',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='username',
        ),
    ]
