# Generated by Django 4.1.5 on 2023-02-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0005_alter_user_inherit_image_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_inherit',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
