# Generated by Django 4.1.5 on 2023-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0006_alter_course_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_inherit',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_inherit',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
