# Generated by Django 4.1.5 on 2023-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0007_user_inherit_is_active_user_inherit_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_inherit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='bio',
        ),
        migrations.AddField(
            model_name='user_inherit',
            name='is_staff',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
