# Generated by Django 4.1.5 on 2023-02-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inherit',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='last name'),
        ),
    ]
