# Generated by Django 4.1.5 on 2023-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0008_alter_user_inherit_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_inherit',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user_inherit',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='user_inherit',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
