# Generated by Django 4.1.5 on 2023-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0009_user_inherit_bio_user_inherit_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
