# Generated by Django 4.1.5 on 2023-01-31 09:24

import Elearning_platform.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0009_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', Elearning_platform.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', Elearning_platform.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user_inherit',
            managers=[
                ('objects', Elearning_platform.models.UserManager()),
            ],
        ),
    ]
