# Generated by Django 4.1.5 on 2023-01-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0010_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_inherit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_inherit',
            name='bio',
        ),
    ]
