# Generated by Django 4.1.5 on 2023-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning_platform', '0011_remove_user_inherit_address_remove_user_inherit_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_inherit',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
